//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 10/8/2017 9:23:33 AM
namespace WinFormsClient.WWIServiceReference
{
    
    /// <summary>
    /// There are no comments for WideWorldImportersEntities in the schema.
    /// </summary>
    public partial class WideWorldImportersEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new WideWorldImportersEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public WideWorldImportersEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "WideWorldImportersModel", "WinFormsClient.WWIServiceReference");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("WinFormsClient.WWIServiceReference", global::System.StringComparison.Ordinal))
            {
                return string.Concat("WideWorldImportersModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Customers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Customer> Customers
        {
            get
            {
                if ((this._Customers == null))
                {
                    this._Customers = base.CreateQuery<Customer>("Customers");
                }
                return this._Customers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Customer> _Customers;
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Order> Orders
        {
            get
            {
                if ((this._Orders == null))
                {
                    this._Orders = base.CreateQuery<Order>("Orders");
                }
                return this._Orders;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Order> _Orders;
        /// <summary>
        /// There are no comments for Customers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToOrders(Order order)
        {
            base.AddObject("Orders", order);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"WideWorldImportersModel\" xmlns=\"http://schemas.microsoft.com/ado/2009" +
                "/11/edm\"><EntityType Name=\"Customer\"><Key><PropertyRef Name=\"CustomerID\" /></Key" +
                "><Property Name=\"CustomerID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=" +
                "\"CustomerName\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"100\" FixedLength=\"f" +
                "alse\" Unicode=\"true\" /><Property Name=\"BillToCustomerID\" Type=\"Edm.Int32\" Nullab" +
                "le=\"false\" /><Property Name=\"CustomerCategoryID\" Type=\"Edm.Int32\" Nullable=\"fals" +
                "e\" /><Property Name=\"BuyingGroupID\" Type=\"Edm.Int32\" /><Property Name=\"PrimaryCo" +
                "ntactPersonID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"AlternateCont" +
                "actPersonID\" Type=\"Edm.Int32\" /><Property Name=\"DeliveryMethodID\" Type=\"Edm.Int3" +
                "2\" Nullable=\"false\" /><Property Name=\"DeliveryCityID\" Type=\"Edm.Int32\" Nullable=" +
                "\"false\" /><Property Name=\"PostalCityID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Pro" +
                "perty Name=\"CreditLimit\" Type=\"Edm.Decimal\" Precision=\"18\" Scale=\"2\" /><Property" +
                " Name=\"AccountOpenedDate\" Type=\"Edm.DateTime\" Nullable=\"false\" Precision=\"0\" /><" +
                "Property Name=\"StandardDiscountPercentage\" Type=\"Edm.Decimal\" Nullable=\"false\" P" +
                "recision=\"18\" Scale=\"3\" /><Property Name=\"IsStatementSent\" Type=\"Edm.Boolean\" Nu" +
                "llable=\"false\" /><Property Name=\"IsOnCreditHold\" Type=\"Edm.Boolean\" Nullable=\"fa" +
                "lse\" /><Property Name=\"PaymentDays\" Type=\"Edm.Int32\" Nullable=\"false\" /><Propert" +
                "y Name=\"PhoneNumber\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"20\" FixedLeng" +
                "th=\"false\" Unicode=\"true\" /><Property Name=\"FaxNumber\" Type=\"Edm.String\" Nullabl" +
                "e=\"false\" MaxLength=\"20\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"De" +
                "liveryRun\" Type=\"Edm.String\" MaxLength=\"5\" FixedLength=\"false\" Unicode=\"true\" />" +
                "<Property Name=\"RunPosition\" Type=\"Edm.String\" MaxLength=\"5\" FixedLength=\"false\"" +
                " Unicode=\"true\" /><Property Name=\"WebsiteURL\" Type=\"Edm.String\" Nullable=\"false\"" +
                " MaxLength=\"256\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"DeliveryAd" +
                "dressLine1\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"60\" FixedLength=\"false" +
                "\" Unicode=\"true\" /><Property Name=\"DeliveryAddressLine2\" Type=\"Edm.String\" MaxLe" +
                "ngth=\"60\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"DeliveryPostalCod" +
                "e\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"10\" FixedLength=\"false\" Unicode" +
                "=\"true\" /><Property Name=\"PostalAddressLine1\" Type=\"Edm.String\" Nullable=\"false\"" +
                " MaxLength=\"60\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"PostalAddre" +
                "ssLine2\" Type=\"Edm.String\" MaxLength=\"60\" FixedLength=\"false\" Unicode=\"true\" /><" +
                "Property Name=\"PostalPostalCode\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"1" +
                "0\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"LastEditedBy\" Type=\"Edm." +
                "Int32\" Nullable=\"false\" /><Property Name=\"ValidFrom\" Type=\"Edm.DateTime\" Nullabl" +
                "e=\"false\" Precision=\"7\" /><Property Name=\"ValidTo\" Type=\"Edm.DateTime\" Nullable=" +
                "\"false\" Precision=\"7\" /><NavigationProperty Name=\"Customers1\" Relationship=\"Wide" +
                "WorldImportersModel.FK_Sales_Customers_BillToCustomerID_Sales_Customers\" ToRole=" +
                "\"Customers1\" FromRole=\"Customers\" /><NavigationProperty Name=\"Customer1\" Relatio" +
                "nship=\"WideWorldImportersModel.FK_Sales_Customers_BillToCustomerID_Sales_Custome" +
                "rs\" ToRole=\"Customers\" FromRole=\"Customers1\" /><NavigationProperty Name=\"Orders\"" +
                " Relationship=\"WideWorldImportersModel.FK_Sales_Orders_CustomerID_Sales_Customer" +
                "s\" ToRole=\"Orders\" FromRole=\"Customers\" /></EntityType><EntityType Name=\"Order\">" +
                "<Key><PropertyRef Name=\"OrderID\" /></Key><Property Name=\"OrderID\" Type=\"Edm.Int3" +
                "2\" Nullable=\"false\" /><Property Name=\"CustomerID\" Type=\"Edm.Int32\" Nullable=\"fal" +
                "se\" /><Property Name=\"SalespersonPersonID\" Type=\"Edm.Int32\" Nullable=\"false\" /><" +
                "Property Name=\"PickedByPersonID\" Type=\"Edm.Int32\" /><Property Name=\"ContactPerso" +
                "nID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"BackorderOrderID\" Type=" +
                "\"Edm.Int32\" /><Property Name=\"OrderDate\" Type=\"Edm.DateTime\" Nullable=\"false\" Pr" +
                "ecision=\"0\" /><Property Name=\"ExpectedDeliveryDate\" Type=\"Edm.DateTime\" Nullable" +
                "=\"false\" Precision=\"0\" /><Property Name=\"CustomerPurchaseOrderNumber\" Type=\"Edm." +
                "String\" MaxLength=\"20\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"IsUn" +
                "dersupplyBackordered\" Type=\"Edm.Boolean\" Nullable=\"false\" /><Property Name=\"Comm" +
                "ents\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Pr" +
                "operty Name=\"DeliveryInstructions\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength" +
                "=\"false\" Unicode=\"true\" /><Property Name=\"InternalComments\" Type=\"Edm.String\" Ma" +
                "xLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"PickingComple" +
                "tedWhen\" Type=\"Edm.DateTime\" Precision=\"7\" /><Property Name=\"LastEditedBy\" Type=" +
                "\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"LastEditedWhen\" Type=\"Edm.DateTim" +
                "e\" Nullable=\"false\" Precision=\"7\" /><NavigationProperty Name=\"Customer\" Relation" +
                "ship=\"WideWorldImportersModel.FK_Sales_Orders_CustomerID_Sales_Customers\" ToRole" +
                "=\"Customers\" FromRole=\"Orders\" /><NavigationProperty Name=\"Orders1\" Relationship" +
                "=\"WideWorldImportersModel.FK_Sales_Orders_BackorderOrderID_Sales_Orders\" ToRole=" +
                "\"Orders1\" FromRole=\"Orders\" /><NavigationProperty Name=\"Order1\" Relationship=\"Wi" +
                "deWorldImportersModel.FK_Sales_Orders_BackorderOrderID_Sales_Orders\" ToRole=\"Ord" +
                "ers\" FromRole=\"Orders1\" /></EntityType><Association Name=\"FK_Sales_Customers_Bil" +
                "lToCustomerID_Sales_Customers\"><End Type=\"WideWorldImportersModel.Customer\" Role" +
                "=\"Customers\" Multiplicity=\"1\" /><End Type=\"WideWorldImportersModel.Customer\" Rol" +
                "e=\"Customers1\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"Custom" +
                "ers\"><PropertyRef Name=\"CustomerID\" /></Principal><Dependent Role=\"Customers1\"><" +
                "PropertyRef Name=\"BillToCustomerID\" /></Dependent></ReferentialConstraint></Asso" +
                "ciation><Association Name=\"FK_Sales_Orders_CustomerID_Sales_Customers\"><End Type" +
                "=\"WideWorldImportersModel.Customer\" Role=\"Customers\" Multiplicity=\"1\" /><End Typ" +
                "e=\"WideWorldImportersModel.Order\" Role=\"Orders\" Multiplicity=\"*\" /><ReferentialC" +
                "onstraint><Principal Role=\"Customers\"><PropertyRef Name=\"CustomerID\" /></Princip" +
                "al><Dependent Role=\"Orders\"><PropertyRef Name=\"CustomerID\" /></Dependent></Refer" +
                "entialConstraint></Association><Association Name=\"FK_Sales_Orders_BackorderOrder" +
                "ID_Sales_Orders\"><End Type=\"WideWorldImportersModel.Order\" Role=\"Orders\" Multipl" +
                "icity=\"0..1\" /><End Type=\"WideWorldImportersModel.Order\" Role=\"Orders1\" Multipli" +
                "city=\"*\" /><ReferentialConstraint><Principal Role=\"Orders\"><PropertyRef Name=\"Or" +
                "derID\" /></Principal><Dependent Role=\"Orders1\"><PropertyRef Name=\"BackorderOrder" +
                "ID\" /></Dependent></ReferentialConstraint></Association></Schema><Schema Namespa" +
                "ce=\"WideWorldImportersService\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/e" +
                "dm\"><EntityContainer Name=\"WideWorldImportersEntities\" m:IsDefaultEntityContaine" +
                "r=\"true\"><EntitySet Name=\"Customers\" EntityType=\"WideWorldImportersModel.Custome" +
                "r\" /><EntitySet Name=\"Orders\" EntityType=\"WideWorldImportersModel.Order\" /><Asso" +
                "ciationSet Name=\"FK_Sales_Customers_BillToCustomerID_Sales_Customers\" Associatio" +
                "n=\"WideWorldImportersModel.FK_Sales_Customers_BillToCustomerID_Sales_Customers\">" +
                "<End Role=\"Customers\" EntitySet=\"Customers\" /><End Role=\"Customers1\" EntitySet=\"" +
                "Customers\" /></AssociationSet><AssociationSet Name=\"FK_Sales_Orders_CustomerID_S" +
                "ales_Customers\" Association=\"WideWorldImportersModel.FK_Sales_Orders_CustomerID_" +
                "Sales_Customers\"><End Role=\"Customers\" EntitySet=\"Customers";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = @""" /><End Role=""Orders"" EntitySet=""Orders"" /></AssociationSet><AssociationSet Name=""FK_Sales_Orders_BackorderOrderID_Sales_Orders"" Association=""WideWorldImportersModel.FK_Sales_Orders_BackorderOrderID_Sales_Orders""><End Role=""Orders"" EntitySet=""Orders"" /><End Role=""Orders1"" EntitySet=""Orders"" /></AssociationSet></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for WideWorldImportersModel.Customer in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CustomerID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Customers")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CustomerID")]
    public partial class Customer : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="customerID">Initial value of CustomerID.</param>
        /// <param name="customerName">Initial value of CustomerName.</param>
        /// <param name="billToCustomerID">Initial value of BillToCustomerID.</param>
        /// <param name="customerCategoryID">Initial value of CustomerCategoryID.</param>
        /// <param name="primaryContactPersonID">Initial value of PrimaryContactPersonID.</param>
        /// <param name="deliveryMethodID">Initial value of DeliveryMethodID.</param>
        /// <param name="deliveryCityID">Initial value of DeliveryCityID.</param>
        /// <param name="postalCityID">Initial value of PostalCityID.</param>
        /// <param name="accountOpenedDate">Initial value of AccountOpenedDate.</param>
        /// <param name="standardDiscountPercentage">Initial value of StandardDiscountPercentage.</param>
        /// <param name="isStatementSent">Initial value of IsStatementSent.</param>
        /// <param name="isOnCreditHold">Initial value of IsOnCreditHold.</param>
        /// <param name="paymentDays">Initial value of PaymentDays.</param>
        /// <param name="phoneNumber">Initial value of PhoneNumber.</param>
        /// <param name="faxNumber">Initial value of FaxNumber.</param>
        /// <param name="websiteURL">Initial value of WebsiteURL.</param>
        /// <param name="deliveryAddressLine1">Initial value of DeliveryAddressLine1.</param>
        /// <param name="deliveryPostalCode">Initial value of DeliveryPostalCode.</param>
        /// <param name="postalAddressLine1">Initial value of PostalAddressLine1.</param>
        /// <param name="postalPostalCode">Initial value of PostalPostalCode.</param>
        /// <param name="lastEditedBy">Initial value of LastEditedBy.</param>
        /// <param name="validFrom">Initial value of ValidFrom.</param>
        /// <param name="validTo">Initial value of ValidTo.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Customer CreateCustomer(
                    int customerID, 
                    string customerName, 
                    int billToCustomerID, 
                    int customerCategoryID, 
                    int primaryContactPersonID, 
                    int deliveryMethodID, 
                    int deliveryCityID, 
                    int postalCityID, 
                    global::System.DateTime accountOpenedDate, 
                    decimal standardDiscountPercentage, 
                    bool isStatementSent, 
                    bool isOnCreditHold, 
                    int paymentDays, 
                    string phoneNumber, 
                    string faxNumber, 
                    string websiteURL, 
                    string deliveryAddressLine1, 
                    string deliveryPostalCode, 
                    string postalAddressLine1, 
                    string postalPostalCode, 
                    int lastEditedBy, 
                    global::System.DateTime validFrom, 
                    global::System.DateTime validTo)
        {
            Customer customer = new Customer();
            customer.CustomerID = customerID;
            customer.CustomerName = customerName;
            customer.BillToCustomerID = billToCustomerID;
            customer.CustomerCategoryID = customerCategoryID;
            customer.PrimaryContactPersonID = primaryContactPersonID;
            customer.DeliveryMethodID = deliveryMethodID;
            customer.DeliveryCityID = deliveryCityID;
            customer.PostalCityID = postalCityID;
            customer.AccountOpenedDate = accountOpenedDate;
            customer.StandardDiscountPercentage = standardDiscountPercentage;
            customer.IsStatementSent = isStatementSent;
            customer.IsOnCreditHold = isOnCreditHold;
            customer.PaymentDays = paymentDays;
            customer.PhoneNumber = phoneNumber;
            customer.FaxNumber = faxNumber;
            customer.WebsiteURL = websiteURL;
            customer.DeliveryAddressLine1 = deliveryAddressLine1;
            customer.DeliveryPostalCode = deliveryPostalCode;
            customer.PostalAddressLine1 = postalAddressLine1;
            customer.PostalPostalCode = postalPostalCode;
            customer.LastEditedBy = lastEditedBy;
            customer.ValidFrom = validFrom;
            customer.ValidTo = validTo;
            return customer;
        }
        /// <summary>
        /// There are no comments for Property CustomerID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CustomerID
        {
            get
            {
                return this._CustomerID;
            }
            set
            {
                this.OnCustomerIDChanging(value);
                this._CustomerID = value;
                this.OnCustomerIDChanged();
                this.OnPropertyChanged("CustomerID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CustomerID;
        partial void OnCustomerIDChanging(int value);
        partial void OnCustomerIDChanged();
        /// <summary>
        /// There are no comments for Property CustomerName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CustomerName
        {
            get
            {
                return this._CustomerName;
            }
            set
            {
                this.OnCustomerNameChanging(value);
                this._CustomerName = value;
                this.OnCustomerNameChanged();
                this.OnPropertyChanged("CustomerName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CustomerName;
        partial void OnCustomerNameChanging(string value);
        partial void OnCustomerNameChanged();
        /// <summary>
        /// There are no comments for Property BillToCustomerID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int BillToCustomerID
        {
            get
            {
                return this._BillToCustomerID;
            }
            set
            {
                this.OnBillToCustomerIDChanging(value);
                this._BillToCustomerID = value;
                this.OnBillToCustomerIDChanged();
                this.OnPropertyChanged("BillToCustomerID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _BillToCustomerID;
        partial void OnBillToCustomerIDChanging(int value);
        partial void OnBillToCustomerIDChanged();
        /// <summary>
        /// There are no comments for Property CustomerCategoryID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CustomerCategoryID
        {
            get
            {
                return this._CustomerCategoryID;
            }
            set
            {
                this.OnCustomerCategoryIDChanging(value);
                this._CustomerCategoryID = value;
                this.OnCustomerCategoryIDChanged();
                this.OnPropertyChanged("CustomerCategoryID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CustomerCategoryID;
        partial void OnCustomerCategoryIDChanging(int value);
        partial void OnCustomerCategoryIDChanged();
        /// <summary>
        /// There are no comments for Property BuyingGroupID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> BuyingGroupID
        {
            get
            {
                return this._BuyingGroupID;
            }
            set
            {
                this.OnBuyingGroupIDChanging(value);
                this._BuyingGroupID = value;
                this.OnBuyingGroupIDChanged();
                this.OnPropertyChanged("BuyingGroupID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _BuyingGroupID;
        partial void OnBuyingGroupIDChanging(global::System.Nullable<int> value);
        partial void OnBuyingGroupIDChanged();
        /// <summary>
        /// There are no comments for Property PrimaryContactPersonID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PrimaryContactPersonID
        {
            get
            {
                return this._PrimaryContactPersonID;
            }
            set
            {
                this.OnPrimaryContactPersonIDChanging(value);
                this._PrimaryContactPersonID = value;
                this.OnPrimaryContactPersonIDChanged();
                this.OnPropertyChanged("PrimaryContactPersonID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PrimaryContactPersonID;
        partial void OnPrimaryContactPersonIDChanging(int value);
        partial void OnPrimaryContactPersonIDChanged();
        /// <summary>
        /// There are no comments for Property AlternateContactPersonID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> AlternateContactPersonID
        {
            get
            {
                return this._AlternateContactPersonID;
            }
            set
            {
                this.OnAlternateContactPersonIDChanging(value);
                this._AlternateContactPersonID = value;
                this.OnAlternateContactPersonIDChanged();
                this.OnPropertyChanged("AlternateContactPersonID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _AlternateContactPersonID;
        partial void OnAlternateContactPersonIDChanging(global::System.Nullable<int> value);
        partial void OnAlternateContactPersonIDChanged();
        /// <summary>
        /// There are no comments for Property DeliveryMethodID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int DeliveryMethodID
        {
            get
            {
                return this._DeliveryMethodID;
            }
            set
            {
                this.OnDeliveryMethodIDChanging(value);
                this._DeliveryMethodID = value;
                this.OnDeliveryMethodIDChanged();
                this.OnPropertyChanged("DeliveryMethodID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _DeliveryMethodID;
        partial void OnDeliveryMethodIDChanging(int value);
        partial void OnDeliveryMethodIDChanged();
        /// <summary>
        /// There are no comments for Property DeliveryCityID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int DeliveryCityID
        {
            get
            {
                return this._DeliveryCityID;
            }
            set
            {
                this.OnDeliveryCityIDChanging(value);
                this._DeliveryCityID = value;
                this.OnDeliveryCityIDChanged();
                this.OnPropertyChanged("DeliveryCityID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _DeliveryCityID;
        partial void OnDeliveryCityIDChanging(int value);
        partial void OnDeliveryCityIDChanged();
        /// <summary>
        /// There are no comments for Property PostalCityID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PostalCityID
        {
            get
            {
                return this._PostalCityID;
            }
            set
            {
                this.OnPostalCityIDChanging(value);
                this._PostalCityID = value;
                this.OnPostalCityIDChanged();
                this.OnPropertyChanged("PostalCityID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PostalCityID;
        partial void OnPostalCityIDChanging(int value);
        partial void OnPostalCityIDChanged();
        /// <summary>
        /// There are no comments for Property CreditLimit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> CreditLimit
        {
            get
            {
                return this._CreditLimit;
            }
            set
            {
                this.OnCreditLimitChanging(value);
                this._CreditLimit = value;
                this.OnCreditLimitChanged();
                this.OnPropertyChanged("CreditLimit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _CreditLimit;
        partial void OnCreditLimitChanging(global::System.Nullable<decimal> value);
        partial void OnCreditLimitChanged();
        /// <summary>
        /// There are no comments for Property AccountOpenedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime AccountOpenedDate
        {
            get
            {
                return this._AccountOpenedDate;
            }
            set
            {
                this.OnAccountOpenedDateChanging(value);
                this._AccountOpenedDate = value;
                this.OnAccountOpenedDateChanged();
                this.OnPropertyChanged("AccountOpenedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _AccountOpenedDate;
        partial void OnAccountOpenedDateChanging(global::System.DateTime value);
        partial void OnAccountOpenedDateChanged();
        /// <summary>
        /// There are no comments for Property StandardDiscountPercentage in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal StandardDiscountPercentage
        {
            get
            {
                return this._StandardDiscountPercentage;
            }
            set
            {
                this.OnStandardDiscountPercentageChanging(value);
                this._StandardDiscountPercentage = value;
                this.OnStandardDiscountPercentageChanged();
                this.OnPropertyChanged("StandardDiscountPercentage");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _StandardDiscountPercentage;
        partial void OnStandardDiscountPercentageChanging(decimal value);
        partial void OnStandardDiscountPercentageChanged();
        /// <summary>
        /// There are no comments for Property IsStatementSent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsStatementSent
        {
            get
            {
                return this._IsStatementSent;
            }
            set
            {
                this.OnIsStatementSentChanging(value);
                this._IsStatementSent = value;
                this.OnIsStatementSentChanged();
                this.OnPropertyChanged("IsStatementSent");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsStatementSent;
        partial void OnIsStatementSentChanging(bool value);
        partial void OnIsStatementSentChanged();
        /// <summary>
        /// There are no comments for Property IsOnCreditHold in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsOnCreditHold
        {
            get
            {
                return this._IsOnCreditHold;
            }
            set
            {
                this.OnIsOnCreditHoldChanging(value);
                this._IsOnCreditHold = value;
                this.OnIsOnCreditHoldChanged();
                this.OnPropertyChanged("IsOnCreditHold");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsOnCreditHold;
        partial void OnIsOnCreditHoldChanging(bool value);
        partial void OnIsOnCreditHoldChanged();
        /// <summary>
        /// There are no comments for Property PaymentDays in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PaymentDays
        {
            get
            {
                return this._PaymentDays;
            }
            set
            {
                this.OnPaymentDaysChanging(value);
                this._PaymentDays = value;
                this.OnPaymentDaysChanged();
                this.OnPropertyChanged("PaymentDays");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PaymentDays;
        partial void OnPaymentDaysChanging(int value);
        partial void OnPaymentDaysChanged();
        /// <summary>
        /// There are no comments for Property PhoneNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PhoneNumber
        {
            get
            {
                return this._PhoneNumber;
            }
            set
            {
                this.OnPhoneNumberChanging(value);
                this._PhoneNumber = value;
                this.OnPhoneNumberChanged();
                this.OnPropertyChanged("PhoneNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PhoneNumber;
        partial void OnPhoneNumberChanging(string value);
        partial void OnPhoneNumberChanged();
        /// <summary>
        /// There are no comments for Property FaxNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FaxNumber
        {
            get
            {
                return this._FaxNumber;
            }
            set
            {
                this.OnFaxNumberChanging(value);
                this._FaxNumber = value;
                this.OnFaxNumberChanged();
                this.OnPropertyChanged("FaxNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FaxNumber;
        partial void OnFaxNumberChanging(string value);
        partial void OnFaxNumberChanged();
        /// <summary>
        /// There are no comments for Property DeliveryRun in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DeliveryRun
        {
            get
            {
                return this._DeliveryRun;
            }
            set
            {
                this.OnDeliveryRunChanging(value);
                this._DeliveryRun = value;
                this.OnDeliveryRunChanged();
                this.OnPropertyChanged("DeliveryRun");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DeliveryRun;
        partial void OnDeliveryRunChanging(string value);
        partial void OnDeliveryRunChanged();
        /// <summary>
        /// There are no comments for Property RunPosition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RunPosition
        {
            get
            {
                return this._RunPosition;
            }
            set
            {
                this.OnRunPositionChanging(value);
                this._RunPosition = value;
                this.OnRunPositionChanged();
                this.OnPropertyChanged("RunPosition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RunPosition;
        partial void OnRunPositionChanging(string value);
        partial void OnRunPositionChanged();
        /// <summary>
        /// There are no comments for Property WebsiteURL in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string WebsiteURL
        {
            get
            {
                return this._WebsiteURL;
            }
            set
            {
                this.OnWebsiteURLChanging(value);
                this._WebsiteURL = value;
                this.OnWebsiteURLChanged();
                this.OnPropertyChanged("WebsiteURL");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _WebsiteURL;
        partial void OnWebsiteURLChanging(string value);
        partial void OnWebsiteURLChanged();
        /// <summary>
        /// There are no comments for Property DeliveryAddressLine1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DeliveryAddressLine1
        {
            get
            {
                return this._DeliveryAddressLine1;
            }
            set
            {
                this.OnDeliveryAddressLine1Changing(value);
                this._DeliveryAddressLine1 = value;
                this.OnDeliveryAddressLine1Changed();
                this.OnPropertyChanged("DeliveryAddressLine1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DeliveryAddressLine1;
        partial void OnDeliveryAddressLine1Changing(string value);
        partial void OnDeliveryAddressLine1Changed();
        /// <summary>
        /// There are no comments for Property DeliveryAddressLine2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DeliveryAddressLine2
        {
            get
            {
                return this._DeliveryAddressLine2;
            }
            set
            {
                this.OnDeliveryAddressLine2Changing(value);
                this._DeliveryAddressLine2 = value;
                this.OnDeliveryAddressLine2Changed();
                this.OnPropertyChanged("DeliveryAddressLine2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DeliveryAddressLine2;
        partial void OnDeliveryAddressLine2Changing(string value);
        partial void OnDeliveryAddressLine2Changed();
        /// <summary>
        /// There are no comments for Property DeliveryPostalCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DeliveryPostalCode
        {
            get
            {
                return this._DeliveryPostalCode;
            }
            set
            {
                this.OnDeliveryPostalCodeChanging(value);
                this._DeliveryPostalCode = value;
                this.OnDeliveryPostalCodeChanged();
                this.OnPropertyChanged("DeliveryPostalCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DeliveryPostalCode;
        partial void OnDeliveryPostalCodeChanging(string value);
        partial void OnDeliveryPostalCodeChanged();
        /// <summary>
        /// There are no comments for Property PostalAddressLine1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PostalAddressLine1
        {
            get
            {
                return this._PostalAddressLine1;
            }
            set
            {
                this.OnPostalAddressLine1Changing(value);
                this._PostalAddressLine1 = value;
                this.OnPostalAddressLine1Changed();
                this.OnPropertyChanged("PostalAddressLine1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PostalAddressLine1;
        partial void OnPostalAddressLine1Changing(string value);
        partial void OnPostalAddressLine1Changed();
        /// <summary>
        /// There are no comments for Property PostalAddressLine2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PostalAddressLine2
        {
            get
            {
                return this._PostalAddressLine2;
            }
            set
            {
                this.OnPostalAddressLine2Changing(value);
                this._PostalAddressLine2 = value;
                this.OnPostalAddressLine2Changed();
                this.OnPropertyChanged("PostalAddressLine2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PostalAddressLine2;
        partial void OnPostalAddressLine2Changing(string value);
        partial void OnPostalAddressLine2Changed();
        /// <summary>
        /// There are no comments for Property PostalPostalCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PostalPostalCode
        {
            get
            {
                return this._PostalPostalCode;
            }
            set
            {
                this.OnPostalPostalCodeChanging(value);
                this._PostalPostalCode = value;
                this.OnPostalPostalCodeChanged();
                this.OnPropertyChanged("PostalPostalCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PostalPostalCode;
        partial void OnPostalPostalCodeChanging(string value);
        partial void OnPostalPostalCodeChanged();
        /// <summary>
        /// There are no comments for Property LastEditedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int LastEditedBy
        {
            get
            {
                return this._LastEditedBy;
            }
            set
            {
                this.OnLastEditedByChanging(value);
                this._LastEditedBy = value;
                this.OnLastEditedByChanged();
                this.OnPropertyChanged("LastEditedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _LastEditedBy;
        partial void OnLastEditedByChanging(int value);
        partial void OnLastEditedByChanged();
        /// <summary>
        /// There are no comments for Property ValidFrom in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime ValidFrom
        {
            get
            {
                return this._ValidFrom;
            }
            set
            {
                this.OnValidFromChanging(value);
                this._ValidFrom = value;
                this.OnValidFromChanged();
                this.OnPropertyChanged("ValidFrom");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _ValidFrom;
        partial void OnValidFromChanging(global::System.DateTime value);
        partial void OnValidFromChanged();
        /// <summary>
        /// There are no comments for Property ValidTo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime ValidTo
        {
            get
            {
                return this._ValidTo;
            }
            set
            {
                this.OnValidToChanging(value);
                this._ValidTo = value;
                this.OnValidToChanged();
                this.OnPropertyChanged("ValidTo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _ValidTo;
        partial void OnValidToChanging(global::System.DateTime value);
        partial void OnValidToChanged();
        /// <summary>
        /// There are no comments for Customers1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Customer> Customers1
        {
            get
            {
                return this._Customers1;
            }
            set
            {
                this._Customers1 = value;
                this.OnPropertyChanged("Customers1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Customer> _Customers1 = new global::System.Data.Services.Client.DataServiceCollection<Customer>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Customer1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Customer Customer1
        {
            get
            {
                return this._Customer1;
            }
            set
            {
                this._Customer1 = value;
                this.OnPropertyChanged("Customer1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Customer _Customer1;
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Order> Orders
        {
            get
            {
                return this._Orders;
            }
            set
            {
                this._Orders = value;
                this.OnPropertyChanged("Orders");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Order> _Orders = new global::System.Data.Services.Client.DataServiceCollection<Order>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for WideWorldImportersModel.Order in the schema.
    /// </summary>
    /// <KeyProperties>
    /// OrderID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Orders")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("OrderID")]
    public partial class Order : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="orderID">Initial value of OrderID.</param>
        /// <param name="customerID">Initial value of CustomerID.</param>
        /// <param name="salespersonPersonID">Initial value of SalespersonPersonID.</param>
        /// <param name="contactPersonID">Initial value of ContactPersonID.</param>
        /// <param name="orderDate">Initial value of OrderDate.</param>
        /// <param name="expectedDeliveryDate">Initial value of ExpectedDeliveryDate.</param>
        /// <param name="isUndersupplyBackordered">Initial value of IsUndersupplyBackordered.</param>
        /// <param name="lastEditedBy">Initial value of LastEditedBy.</param>
        /// <param name="lastEditedWhen">Initial value of LastEditedWhen.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Order CreateOrder(int orderID, int customerID, int salespersonPersonID, int contactPersonID, global::System.DateTime orderDate, global::System.DateTime expectedDeliveryDate, bool isUndersupplyBackordered, int lastEditedBy, global::System.DateTime lastEditedWhen)
        {
            Order order = new Order();
            order.OrderID = orderID;
            order.CustomerID = customerID;
            order.SalespersonPersonID = salespersonPersonID;
            order.ContactPersonID = contactPersonID;
            order.OrderDate = orderDate;
            order.ExpectedDeliveryDate = expectedDeliveryDate;
            order.IsUndersupplyBackordered = isUndersupplyBackordered;
            order.LastEditedBy = lastEditedBy;
            order.LastEditedWhen = lastEditedWhen;
            return order;
        }
        /// <summary>
        /// There are no comments for Property OrderID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int OrderID
        {
            get
            {
                return this._OrderID;
            }
            set
            {
                this.OnOrderIDChanging(value);
                this._OrderID = value;
                this.OnOrderIDChanged();
                this.OnPropertyChanged("OrderID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _OrderID;
        partial void OnOrderIDChanging(int value);
        partial void OnOrderIDChanged();
        /// <summary>
        /// There are no comments for Property CustomerID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CustomerID
        {
            get
            {
                return this._CustomerID;
            }
            set
            {
                this.OnCustomerIDChanging(value);
                this._CustomerID = value;
                this.OnCustomerIDChanged();
                this.OnPropertyChanged("CustomerID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CustomerID;
        partial void OnCustomerIDChanging(int value);
        partial void OnCustomerIDChanged();
        /// <summary>
        /// There are no comments for Property SalespersonPersonID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SalespersonPersonID
        {
            get
            {
                return this._SalespersonPersonID;
            }
            set
            {
                this.OnSalespersonPersonIDChanging(value);
                this._SalespersonPersonID = value;
                this.OnSalespersonPersonIDChanged();
                this.OnPropertyChanged("SalespersonPersonID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SalespersonPersonID;
        partial void OnSalespersonPersonIDChanging(int value);
        partial void OnSalespersonPersonIDChanged();
        /// <summary>
        /// There are no comments for Property PickedByPersonID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> PickedByPersonID
        {
            get
            {
                return this._PickedByPersonID;
            }
            set
            {
                this.OnPickedByPersonIDChanging(value);
                this._PickedByPersonID = value;
                this.OnPickedByPersonIDChanged();
                this.OnPropertyChanged("PickedByPersonID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _PickedByPersonID;
        partial void OnPickedByPersonIDChanging(global::System.Nullable<int> value);
        partial void OnPickedByPersonIDChanged();
        /// <summary>
        /// There are no comments for Property ContactPersonID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ContactPersonID
        {
            get
            {
                return this._ContactPersonID;
            }
            set
            {
                this.OnContactPersonIDChanging(value);
                this._ContactPersonID = value;
                this.OnContactPersonIDChanged();
                this.OnPropertyChanged("ContactPersonID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ContactPersonID;
        partial void OnContactPersonIDChanging(int value);
        partial void OnContactPersonIDChanged();
        /// <summary>
        /// There are no comments for Property BackorderOrderID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> BackorderOrderID
        {
            get
            {
                return this._BackorderOrderID;
            }
            set
            {
                this.OnBackorderOrderIDChanging(value);
                this._BackorderOrderID = value;
                this.OnBackorderOrderIDChanged();
                this.OnPropertyChanged("BackorderOrderID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _BackorderOrderID;
        partial void OnBackorderOrderIDChanging(global::System.Nullable<int> value);
        partial void OnBackorderOrderIDChanged();
        /// <summary>
        /// There are no comments for Property OrderDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime OrderDate
        {
            get
            {
                return this._OrderDate;
            }
            set
            {
                this.OnOrderDateChanging(value);
                this._OrderDate = value;
                this.OnOrderDateChanged();
                this.OnPropertyChanged("OrderDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _OrderDate;
        partial void OnOrderDateChanging(global::System.DateTime value);
        partial void OnOrderDateChanged();
        /// <summary>
        /// There are no comments for Property ExpectedDeliveryDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime ExpectedDeliveryDate
        {
            get
            {
                return this._ExpectedDeliveryDate;
            }
            set
            {
                this.OnExpectedDeliveryDateChanging(value);
                this._ExpectedDeliveryDate = value;
                this.OnExpectedDeliveryDateChanged();
                this.OnPropertyChanged("ExpectedDeliveryDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _ExpectedDeliveryDate;
        partial void OnExpectedDeliveryDateChanging(global::System.DateTime value);
        partial void OnExpectedDeliveryDateChanged();
        /// <summary>
        /// There are no comments for Property CustomerPurchaseOrderNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CustomerPurchaseOrderNumber
        {
            get
            {
                return this._CustomerPurchaseOrderNumber;
            }
            set
            {
                this.OnCustomerPurchaseOrderNumberChanging(value);
                this._CustomerPurchaseOrderNumber = value;
                this.OnCustomerPurchaseOrderNumberChanged();
                this.OnPropertyChanged("CustomerPurchaseOrderNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CustomerPurchaseOrderNumber;
        partial void OnCustomerPurchaseOrderNumberChanging(string value);
        partial void OnCustomerPurchaseOrderNumberChanged();
        /// <summary>
        /// There are no comments for Property IsUndersupplyBackordered in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsUndersupplyBackordered
        {
            get
            {
                return this._IsUndersupplyBackordered;
            }
            set
            {
                this.OnIsUndersupplyBackorderedChanging(value);
                this._IsUndersupplyBackordered = value;
                this.OnIsUndersupplyBackorderedChanged();
                this.OnPropertyChanged("IsUndersupplyBackordered");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsUndersupplyBackordered;
        partial void OnIsUndersupplyBackorderedChanging(bool value);
        partial void OnIsUndersupplyBackorderedChanged();
        /// <summary>
        /// There are no comments for Property Comments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Comments
        {
            get
            {
                return this._Comments;
            }
            set
            {
                this.OnCommentsChanging(value);
                this._Comments = value;
                this.OnCommentsChanged();
                this.OnPropertyChanged("Comments");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Comments;
        partial void OnCommentsChanging(string value);
        partial void OnCommentsChanged();
        /// <summary>
        /// There are no comments for Property DeliveryInstructions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DeliveryInstructions
        {
            get
            {
                return this._DeliveryInstructions;
            }
            set
            {
                this.OnDeliveryInstructionsChanging(value);
                this._DeliveryInstructions = value;
                this.OnDeliveryInstructionsChanged();
                this.OnPropertyChanged("DeliveryInstructions");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DeliveryInstructions;
        partial void OnDeliveryInstructionsChanging(string value);
        partial void OnDeliveryInstructionsChanged();
        /// <summary>
        /// There are no comments for Property InternalComments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string InternalComments
        {
            get
            {
                return this._InternalComments;
            }
            set
            {
                this.OnInternalCommentsChanging(value);
                this._InternalComments = value;
                this.OnInternalCommentsChanged();
                this.OnPropertyChanged("InternalComments");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _InternalComments;
        partial void OnInternalCommentsChanging(string value);
        partial void OnInternalCommentsChanged();
        /// <summary>
        /// There are no comments for Property PickingCompletedWhen in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> PickingCompletedWhen
        {
            get
            {
                return this._PickingCompletedWhen;
            }
            set
            {
                this.OnPickingCompletedWhenChanging(value);
                this._PickingCompletedWhen = value;
                this.OnPickingCompletedWhenChanged();
                this.OnPropertyChanged("PickingCompletedWhen");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _PickingCompletedWhen;
        partial void OnPickingCompletedWhenChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnPickingCompletedWhenChanged();
        /// <summary>
        /// There are no comments for Property LastEditedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int LastEditedBy
        {
            get
            {
                return this._LastEditedBy;
            }
            set
            {
                this.OnLastEditedByChanging(value);
                this._LastEditedBy = value;
                this.OnLastEditedByChanged();
                this.OnPropertyChanged("LastEditedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _LastEditedBy;
        partial void OnLastEditedByChanging(int value);
        partial void OnLastEditedByChanged();
        /// <summary>
        /// There are no comments for Property LastEditedWhen in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime LastEditedWhen
        {
            get
            {
                return this._LastEditedWhen;
            }
            set
            {
                this.OnLastEditedWhenChanging(value);
                this._LastEditedWhen = value;
                this.OnLastEditedWhenChanged();
                this.OnPropertyChanged("LastEditedWhen");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _LastEditedWhen;
        partial void OnLastEditedWhenChanging(global::System.DateTime value);
        partial void OnLastEditedWhenChanged();
        /// <summary>
        /// There are no comments for Customer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Customer Customer
        {
            get
            {
                return this._Customer;
            }
            set
            {
                this._Customer = value;
                this.OnPropertyChanged("Customer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Customer _Customer;
        /// <summary>
        /// There are no comments for Orders1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Order> Orders1
        {
            get
            {
                return this._Orders1;
            }
            set
            {
                this._Orders1 = value;
                this.OnPropertyChanged("Orders1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Order> _Orders1 = new global::System.Data.Services.Client.DataServiceCollection<Order>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Order1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Order Order1
        {
            get
            {
                return this._Order1;
            }
            set
            {
                this._Order1 = value;
                this.OnPropertyChanged("Order1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Order _Order1;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
